<?php

require '../../../vendor/autoload.php';

if(!perch_member_logged_in()){
	header("location:/");
}

$planID = $_GET['planID'];
$date = $_GET['date'];
$time = $_GET['time'];

$plan = hello_church_get_plan($planID, $date, $time);

$plan = json_decode($plan, true);

foreach($plan as $type => $item){
					
	$typeParts = explode("_", $type);
	$type = $typeParts[0];
	
	if($type=='heading'){
		echo '<h2>'.$item.'</h2>';
	}
	if($type=='text'){
		echo '<p>'.nl2br($item).'</p>';
	}
	if($type=='youtube'){
		echo preg_replace("/\s*[a-zA-Z\/\/:\.]*youtu.be\/([a-zA-Z0-9\-_]+)([a-zA-Z0-9\/\*\-\_\?\&\;\%\=\.]*)/i","<iframe width=\"420\" height=\"315\" src=\"//www.youtube.com/embed/$1\" frameborder=\"0\" allowfullscreen></iframe>",$item);
	}
	if($type=='bible'){
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();
		
		curl_setopt($ch, CURLOPT_URL, 'https://api.esv.org/v3/passage/html/?include-footnotes=false&q='.urlencode($item));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
		
		
		$headers = array();
		$headers[] = 'Authorization: Token 0aa221b3e0dbb4ca9d1abe0438ceac27e2b81cee';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		
		$resultESV = curl_exec($ch);
		if (curl_errno($ch)) {
		    echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		$json = json_decode($resultESV,true);
		echo '<div class="bible flow">'.$json['passages'][0].'</div>';

	}
	if($type=='link'){
		
		if($typeParts[2]=='text'){
			$buttonText = $item;	
		}else{
			echo '<p><a class="button primary" href="'.$item.'">'.$buttonText.'</a></p>';
		}
		
	}
	
}